version: '3.7'

services:

  api:
    build: ./api
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./api/:/api/
    ports:
      - 8001:8000
    environment:
      - ./api/.env
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./api/.env

volumes:
  postgres_data:
