version: '3.7'

services:

  api:
    build: ./api
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./api/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://db_username:db_password@db/db_dev
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_username
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=movie_db_dev

volumes:
  postgres_data:
